- name: Create directories
  hosts: all

  tasks:
    - name: Create directories
      file:
        path: "~/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - accumulo
        - geomesa
        - hadoop
        - spark
        - toree
        - zookeeper
        - files

    - name: Change owner for hadoop disk
      become: yes
      command: chown hadoop:hadoop -R /data/hdfs

    - name: Create dir for HDFS DFS
      become: yes
      file:
        path: /data/hdfs/ssd0/dfs
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'

    - name: Create dir for HDFS Namenode
      become: yes
      file:
        path: /data/hdfs/ssd0/namenode
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'

    - name: Create dir for HDFS tmp
      become: yes     
      file:
        path: /data/tmp/hdfs
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'