- name: Create directories, download files and extract
  hosts: all

  tasks:
    - name: Create directories
      file:
        path: "~/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - accumulo
        - geomesa
        - hadoop
        - spark
        - toree
        - zookeeper
        - files