- name: Install Python and virtualenvwrapper
  hosts: all
  become: true
  tasks:
    - name: Add the deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Python 3.10
      apt:
        name: python3.10
        state: present

    - name: Install virtualenvwrapper
      apt:
        name: virtualenvwrapper
        state: present