- name: Install zsh and ohmyzsh for Hadoop user
  hosts: all
  become: true
  vars:
    zsh_dependencies: []
  tasks:
    - name: Ensure Zsh with dependencies are installed
      apt:
        name: "{{ ['zsh'] + zsh_dependencies }}"
        state: present
        update_cache: yes

    - name: Ensure zsh is the default shell for hadoop user
      user:
        name: hadoop
        shell: /usr/bin/zsh

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh

    - name: Run Oh My Zsh installation script as hadoop user
      become: true
      command: sudo -u hadoop sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"

    - name: Clean up Oh My Zsh installation script
      file:
        path: /tmp/install_ohmyzsh.sh
        state: absent
