- name: Install Packages
  hosts: all
  become: true
  tasks:
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    # - name: Install OpenJDK 11
    #   apt:
    #     name: openjdk-11-jdk
    #     state: present

    - name: Add the deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Python 3.10
      apt:
        name: python3.10
        state: present

    - name: Install virtualenvwrapper
      apt:
        name: virtualenvwrapper
        state: present
        
    - name: Ensure the directory /data/datastore/hadoop/.local/bin/ exists
      file:
        path: /data/datastore/hadoop/.local/bin/
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'

    - name: Copy virtualenvwrapper.sh to the new directory
      copy:
        src: /usr/share/virtualenvwrapper/virtualenvwrapper.sh
        dest: /data/datastore/hadoop/.local/bin/virtualenvwrapper.sh
        owner: hadoop
        group: hadoop
        mode: '0644'

    - name: Ensure the directory /data/tmp/zookeeper exists
      file:
        path: /data/tmp/zookeeper
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'