- name: Setup Accumulo
  hosts: all

  tasks:
    - name: Accumulo
    block:
      - name: Download and extract Accumulo
        block:
          - name: Download Accumulo tarball
            get_url:
              url: "https://archive.apache.org/dist/accumulo/2.0.1/accumulo-2.0.1-bin.tar.gz"
              dest: "~/files/accumulo-2.0.1.tar.gz"
          
          - name: Extract Accumulo tarball
            unarchive:
              src: "~/files/accumulo-2.0.1.tar.gz"
              dest: "~/accumulo"
              remote_src: yes